### ISSUE TITLE
Support organized point cloud

### ISSUE THREAD

**Issue by wkentaro** [dimatura/pypcd#4]
Currently it supports only height=1.
- PointCloud.from_array: https://github.com/dimatura/pypcd/blob/master/pypcd/pypcd.py#L723
- PointCloud.from_msg: https://github.com/dimatura/pypcd/blob/master/pypcd/pypcd.py#L693

**Comment by wkentaro** [comment]
@dimatura 
Could you please explain how to manage the tests?
I tried below but got errors in master branch.
```
% nosetests -vs pypcd/tests/test_pypcd.py
pypcd.tests.test_pypcd.test_parse_header ... ok
pypcd.tests.test_pypcd.test_from_path ... ERROR
pypcd.tests.test_pypcd.test_add_fields ... ERROR
pypcd.tests.test_pypcd.test_path_roundtrip_ascii ... ERROR
pypcd.tests.test_pypcd.test_path_roundtrip_binary ... ERROR
pypcd.tests.test_pypcd.test_path_roundtrip_binary_compressed ... ERROR
pypcd.tests.test_pypcd.test_cat_pointclouds ... ERROR
pypcd.tests.test_pypcd.test_ascii_bin1 ... ERROR

======================================================================
ERROR: pypcd.tests.test_pypcd.test_from_path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/.local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_from_path() takes exactly 1 argument (0 given)

======================================================================
ERROR: pypcd.tests.test_pypcd.test_add_fields
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/.local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_add_fields() takes exactly 1 argument (0 given)

======================================================================
ERROR: pypcd.tests.test_pypcd.test_path_roundtrip_ascii
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/.local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_path_roundtrip_ascii() takes exactly 1 argument (0 given)

======================================================================
ERROR: pypcd.tests.test_pypcd.test_path_roundtrip_binary
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/.local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_path_roundtrip_binary() takes exactly 1 argument (0 given)

======================================================================
ERROR: pypcd.tests.test_pypcd.test_path_roundtrip_binary_compressed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/.local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_path_roundtrip_binary_compressed() takes exactly 1 argument (0 given)

======================================================================
ERROR: pypcd.tests.test_pypcd.test_cat_pointclouds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/.local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_cat_pointclouds() takes exactly 1 argument (0 given)

======================================================================
ERROR: pypcd.tests.test_pypcd.test_ascii_bin1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/.local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_ascii_bin1() takes exactly 2 arguments (0 given)

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (errors=7)
```

**Comment by dimatura** [comment]
Oh sorry - should have specified - I use py.test, not nose.
