### ISSUE TITLE
NotImplementedError: ROS sensor_msgs not found

### ISSUE THREAD

**Issue by MeHelge** [dimatura/pypcd#42]
i am am getting this error. What am i doing wrong ?

`  [ERROR] [1701354711.882691, 1693481923.663362]: bad callback: <function callback_py at 0x7f4753d5a9d0>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/workspaces/noetic_dev/src/ros_numpy/src/ros_numpy/runfile.py", line 61, in callback_py
    pc = pypcd.PointCloud.from_msg(data)
  File "/usr/local/lib/python3.8/dist-packages/pypcd/pypcd.py", line 780, in from_msg
    raise NotImplementedError('ROS sensor_msgs not found')
NotImplementedError: ROS sensor_msgs not found`

**Comment by Merwanski** [comment]
Hey @MeHelge 
Try the following script to extract the point cloud data 
https://gist.github.com/Merwanski/bef218ff3b7472d5ac787e1392116fd7
